- name: 京东方
  code: '000725.SZ'
- name: 隆基股份
  code: '601012'
- name: 比亚迪
  code: '2694'
- name: 贵州茅台
  code: '600519'
- name: 永辉超市
  code: '601933'
- name: 中国平安
  code: '601318'
- name: 南方航空
  code: '600029'
- name: 亿纬锂能
  code: '300014'
- name: 迈瑞医疗
  code: '300760'
- name: 紫光国微
  code: '2049'
- name: 东方雨虹
  code: '2271'
- name: 宁德时代
  code: '300750'
- name: 五粮液
  code: '858'
- name: 天赐材料
  code: '2709'
- name: 长春高新
  code: '661'
- name: 兆易创新
  code: '603986'
- name: 玉马遮阳
  code: '300993'