- name: 京东方A
  code: '000725'
  info: >
    <p>
    这家公司拥有潜力，但是在购买这家公司股票之前，一定要看清它所存在的一些问题：从他历史营收增长看起来，我们相信营收还会持续现在的稳定增长，但是这家公司利润和现金流在过去二十年始终不是很理想，它的利润大部分来自于政府补助，除开17年行情大幅拉伸以外，只有在2020年的三季度实现了营收，利润，扣非净利润的大幅增长。这种势头是否能持续下去，是一个未知数。现在中国政府大力支持国家高端产业链的发展，所以我们认为政府补助应该不会在短期内有太大的变化，即使扣非净利润看似不高，因此不必担心现金流会出现任何的问题。
    问题在于，管理层是否真的有能力和远见，将过去二十年中投入的大量资金，转换为真正的利润。如果刨去政府补助，他们的ROE（净资产回报率）几乎处于全行业垫底的地位。这让我们不得不质疑
    管理层的能力。它们并非超高速发展的网络科技公司，而是一家硬件企业，这种长时间不盈利的状态，或许是为了未来行情回暖利润爆发前的准备，亦或是公司管理层无能的表现，我们比较倾向于它属于后者。
    </p>
- name: 隆基股份
  code: '601012'
  info: >
    <p>隆基股份 光伏龙头 俗称光伏茅，让我们看看为啥这么牛逼</p>
    <p>隆基股份公司长期专注于为全球客户提供高效单晶太阳能发电解决方案，主要从事单晶硅棒、硅片、电池和组件的研发、生产和销售，光伏电站的开发及系统解决方案的提供业务。 </p>
    <p>近年来，全球新能源可持续发展成为主要趋势，可再生能源成为驱动全球能源格局变化的主要力量。对于清洁能源的需求越来越高，光伏太阳能的占比也越来越高。随着光伏行业技术不断进步和度电成本的下降，光伏发电的成本优势和普遍推广使用的优势愈加显著，目前光伏发电已在全球很多国家和地区成为最具竞争力的电力能源。在海外市场需求快速增长的驱动下，光伏发电应用在全球范围内迅速拓展，海外市场增长明显。同时中国光伏行业发展规模持续领跑全球。</p>
    <p>作为国内光伏的龙头企业，隆基股份是全球最大的单晶硅片制造商。发展策略：快速成长，全球经营，占据行业优势地位；科技引领，效率驱动，构筑长期竞争能力。持续密切关注市场需求及产品趋势，不断聚焦提升客户价值和服务满意度，强化技术创新，全面提升全球化运营能力，产品策划与管理能力，加快单晶产品的产出，降本增效，实现产品技术，成本与市场“领跑”，巩固全球单晶龙头地位；扩大现有竞争优势，建立持久新优势，加强内外部风险的识别、防控和应对，赋能赋权激发组织活力。</p>
    <p>
    1、2020 年产能目标
      截至2020年底，单晶硅片年产能达到75GW以上,单晶组件产能达到30GW以上。
    2、2020 年业务目标
      2020年度单晶硅片出货量目标58GW（含自用），组件出货量目标20GW（含自用）。
    3、2020 年收入目标
      2020 年计划实现营业收入 496 亿元。
    </p>
- name: 比亚迪
  code: '2594'
  info: >
    比亚迪从生产电池起家，现如今已经是中国电动车领域的龙头。
- name: 贵州茅台
  code: '600519'
  info: >
    <p>贵州茅台在A股市值第一，让我们看看为啥这么牛逼</p>
    <p>公司主营贵州茅台酒系列产品的生产和销售，同时进行饮料、食品、包装材料的生产和销售，防伪技术开发，信息产业相关产品的研制开发。贵州茅台酒股份有限公司茅台酒年生产量已突破一万吨；43°、38°、33°茅台酒拓展了茅台酒家族低度酒的发展空间；茅台王子酒、茅台迎宾酒满足了中低档消费者的需求；15年、30年、50年、80年陈年茅台酒填补了我国极品酒、年份酒、陈年老窖的空白；在国内独创年代梯级式的产品开发模式。形成了低度、高中低档、极品三大系列70多个规格品种，全方位跻身市场，从而占据了白酒市场制高点，称雄于中国极品酒市场。</p>
    <p>贵州茅台酒股份有限公司（上交所：600519，简称：贵州茅台），1999年，贵州茅台酒股份有限公司由中国贵州茅台酒厂有限责任公司、贵州茅台酒厂技术开发公司、贵州省轻纺集体工业联社、深圳清华大学研究院、中国食品发酵工业研究所、北京糖业烟酒公司、江苏省糖烟酒总公司、上海捷强烟草糖酒（集团）有限公司等八家公司共同发起
    公司主营贵州茅台酒及系列产品的生产和销售，同时进行饮料、食品、包装材料的生产和销售，防伪技术开发，信息产业相关产品的研制开发。
    </p>
    <h5>主要业务</h5>
    <p>公司主要业务是茅台酒及系列酒的生产与销售。主导产品“贵州茅台酒”是世界三大蒸馏名 酒之一，也是集国家地理标志产品、有机食品和国家非物质文化遗产于一身的白酒品牌。 
    公司经营模式为：采购原料—生产产品—销售产品。原料采购根据公司生产和销售计划进行；产品生产工艺流程为：制曲—制酒—贮存—勾兑—包装；销售模式为：公司产品通过直销和 批发代理渠道进行销售。直销渠道指自营渠道，批发代理渠道指社会经销商、商超、电商等渠道。 
    </p>
    <h4>2020报告期内主要经营情况</h4>
    <p>2020报告期内主要经营情况 一是主要指标稳定增长。1.收入利润保持增长。公司实现营业总收入 979.93 亿元，同比增 长 10.29%；其中酒类收入 948.22 亿元，同比增长 11.10%；实现归属于母公司所有者的净利润 466.97 亿元，同比增长 13.33%。2.毛利率保持增长。酒类销售毛利率 91.48%，同比增长 0.11 个百分点；其中茅台酒销售毛利率 93.99%，同比增加 0.21 个百分点。3.产质量稳中有升。生产 基酒 7.52 万吨，同比增长 0.15%；其中生产茅台酒基酒 5.02 万吨，同比增长 0.63%。产品出厂 合格率 100%。 二是全力筑牢抗疫防线。认真贯彻落实党中央、国务院和省委、省政府关于统筹做好疫情防 控和经济社会发展工作会议精神，坚持疫情防控和生产经营“两手抓、两不误”，建立联防联控 机制，筑牢疫情坚固防线，实现全公司“零疑似、零确诊”，确保了员工生命安全和身体健康； 在行业内率先复工复产复市，把损失和影响降到最低，稳定了高质量发展大局，交出了抗击疫情 的优异答卷。 三是深化改革成效显著。研究形成机构改革方案，完成了和义兴分公司等机构改革，职能体 系更加完善，服务更加高效。持续深化营销体制改革，积极丰富和拓展营销渠道，规范社会渠道 管理，形成多渠道协同发展的良好格局，提升了综合效益；多措并举推动控价稳市，增强了市场 抗风险能力，保障了疫情形势下的市场稳定态势。 四是项目建设持续推进。“十三五”茅台酒技改项目全面完成投产，新增茅台酒基酒设计产 能 4,032 吨；3 万吨酱香系列酒技改项目有序推进，新增系列酒基酒设计产能 4,015 吨；完成固 定资产投资 21.72 亿元。 </p>
    <h4>行业格局和趋势 </h4>
    <p>1.格局和趋势。2020 年，白酒行业虽受新冠疫情影响，但白酒行业具有强大的抗压性、生命力和恢复力，白酒产业结构持续优化、市场活力有序释放、科创动能有效转化、产品品质稳步提升，发展质量和韧性显著增强。一是产销稳中微降。随着供给侧结构性改革深化，规模以上白酒企业产销量略有下降；二是效益进中向好。在转型升级背景下，行业提质增效成果显著，高质量发展基础牢固；三是格局不断优化，市场份额逐渐向头部企业集中。</p>
    <p>2.公司竞争优势。一是竞争力突出。公司拥有著名的品牌、卓越的品质、悠久的文化、厚重的历史积淀、独特的环境、特殊的工艺等优势所组成的核心竞争力，是公司高质量发展的坚实基础；二是市场基础牢固。公司市场消费人群稳定、渠道资源丰富，市场布局完善，销售体系成熟；三是系统化发展能力强劲。公司拥有规模化的产品生产和配套能力，实力雄厚的管理、技术、营销团队以及精通制酒、制曲、勾兑、品评的工匠队伍。</p>
    <h4>公司发展战略</h4>
    <p>“十四五”规划期间，公司将立足新发展阶段、贯彻新发展理念、融入新发展格局，坚持稳中求进工作总基调，以高质量发展统揽全局，以聚主业、调结构、强配套、构生态为发展思路,筑牢“质量、安全、环保”三条生命线，推进品质茅台、绿色茅台、活力茅台、文化茅台和阳光茅台建设，巩固茅台酒世界蒸馏酒第一品牌地位，推动茅台高质量发展、大踏步前进。 </p>
- name: 永辉超市
  code: '601933'
  info: >
    <p>永辉超市卖的东西便宜又新鲜</p>
- name: 中国平安
  code: '601318'
  info: >
    <p>中国平安是中国最大的保险公司</p>
- name: 南方航空
  code: '600029'
  info: >
    <p>南方航空是个航空公司</p>
- name: 亿纬锂能
  code: '300014'
  info: >
    <p>惠州亿纬锂能股份有限公司（简称：亿纬锂能）成立于2001年，是一家专注于锂电池创新发展的国家高新技术企业，公司秉承高质量发展战略，持续聚焦高端锂电池技术及产品，拥有锂原电池、小型锂离子电池、动力电池核心技术，致力于为物联网、能源互联网提供绿色高能、安全可靠的电源解决方案。（股票代码：300014.SZ）</p>
- name: 迈瑞医疗
  code: '300760'
  info: >
    <p>公司主要从事医疗器械的研发、制造、营销及服务，始终以客户需求为导向，致力于为全球医疗机构 提供优质产品和服务。公司融合创新，紧贴临床需求，支持医疗机构提供优质的医疗服务，从而帮助世界 各地改善医疗条件、降低医疗成本。历经多年的发展，公司已经成为中国最大、全球领先的医疗器械以及 解决方案供应商。公司总部设在中国深圳，在北美、欧洲、亚洲、非洲、拉美等地区的超过30个国家设有 39家境外子公司；在国内设有20家子公司，超过40家分支机构；已建立起基于全球资源配置的研发创新平 台，设有九大研发中心，分布在深圳、武汉、南京、北京、西安、成都、美国硅谷、美国新泽西和美国西 雅图，形成了庞大的全球化研发、营销及服务网络。 
    </p>
    <h6>公司主要产品</h6>
    <p>公司主要产品覆盖三大领域：生命信息与支持、体外诊断以及医学影像，拥有国内同行业中最全的产 品线，以安全、高效、易用的“一站式”整体解决方案满足临床需求。</p>
    <p>在生命信息与支持领域，公司产品包括监护仪、除颤仪、麻醉机、呼吸机、心电图机、手术床、手术 灯、吊塔吊桥、输注泵、以及手术室/重症监护室（OR/ICU）整体解决方案等一系列用于生命信息监测与 支持的仪器和解决方案的组合，以及包括外科腔镜摄像系统、冷光源、气腹机、光学内窥镜、微创手术器 械及手术耗材等产品在内的微创外科系列产品。
    在体外诊断领域，公司为实验室、诊所和医院提供一系列全自动及半自动的体外诊断产品，主要包括 血液细胞分析仪、生化分析仪、化学发光免疫分析仪、凝血分析仪、尿液分析仪、微生物诊断系统等及相 关试剂，通过人体的样本（如血液、体液、组织等）的检测而获取临床诊断信息。针对2020年突然爆发的 新冠疫情，公司推出了灵敏度高特异性好的新冠 IgG/IgM 抗体检测试剂产品。
    </p>
    <p>在医学影像领域，公司产品包括超声诊断系统、数字X射线成像系统和 PACS。在超声诊断系统领域， 为医院、诊所、影像中心等提供从高端覆盖到低端的全系列超声诊断系统，以及逐步细分应用于放射、妇 产、介入、急诊、麻醉、重症、肝纤等不同临床专业的专用解决方案。在数字X射线成像领域，公司为放 射科、ICU、急诊科提供包括移动式、双立柱式和悬吊式在内的多种数字化成像解决方案。
    </p>
    <h6>未来发展</h6>
    <p>面向未来的后疫情时代，公司将增加对体外诊断领域的自动化、智能化流水线、以及微生物子业务和生命信息与支持领域的呼吸机子业务、院内和跨院区监护及互联互通等方面的研发投入，重点培育微创外 科、兽用、AED等细分赛道。同时，积极探索超高端彩超、分子诊断、骨科等种子业务，并采用内外部研 发相结合的方式，加快在这些领域的研发节奏。公司将继续丰富“瑞智联” IT 解决方案，构建设备全息 数据库，与医院已有的临床数据库互补并有机结合，助力大数据科研；继续开发“瑞影云++”影像云平台 的应用场景，助力提升医共体/医联体整体诊疗水平。 
    目前，公司产品及解决方案已应用于全球190多个国家和地区。在国内市场，公司产品覆盖中国近11 万家医疗机构和99%以上的三甲医院，包括全国知名的北京协和医院、上海市公共卫生临床中心、上海瑞 金医院等。在国际市场，作为全球领先医疗机构的长期伙伴，如梅奥诊所、约翰·霍普金斯医院、麻省总医 院、克利夫兰医学中心的长期合作伙伴，公司已赢得美国、英国、德国、法国、意大利、西班牙等国家医 疗机构的广泛认可。 
    </p>
    <h6>2020年概况</h6>
    <p>2020年，随着新冠疫情在全球范围的爆发，生命信息与支持业务的监护仪、呼吸机、输注泵和医学影 像业务的便携彩超、移动DR的需求量大幅增长，其中对生命信息与支持业务的拉动作用尤为显著。从2020 年第二季度开始，公司开始向海外市场出口新冠 IgG/IgM 抗体检测试剂，弥补了疫情对体外诊断业务造 成的部分影响，同时得益于国内常规试剂消耗逐步恢复，体外诊断业务在报告期内实现了加速恢复。经过 此轮疫情的考验，公司在国内和国际市场的品牌影响力和认知度得到了极大的提升，实现了众多高端市场的客户群突破，给公司未来的增长带来了更多的机会。同时公司持续加强内部管理，改善经营效率，并且 受到疫情期内营销推广和差旅减少的影响，经营业绩呈现健康良好的增长态势。
    </p>
    <p>报告期内，公司实现营业收入 2,102,584.64 万元，较上年同期增长 27.00%；利润总额 743,844.03 万 元，较上年同期增长 38.56%；实现归属于上市公司股东的净利润 665,767.61 万元，较上年同期增长 42.24%。 
    </p>
- name: 紫光国微
  code: '2049'
  info: >
    <p>
    紫光国芯微电子股份有限公司（简称“紫光国微”，SZ002049）是紫光集团有限公司旗下核心企业，是国内最大的集成电路设计上市公司之一。公司以智慧芯片为核心，聚焦数字安全、智能计算、功率与电源管理、高可靠集成电路等业务，是领先的芯片产品和解决方案提供商，产品广泛应用于金融、电信、政务、汽车、工业互联、物联网等领域。
    公司以“用芯成就客户、共创智慧世界”为使命，以“智慧芯片领导者”为愿景，坚持“技术领先、全球发展、高效运营” 三条路径，深耕“智慧网联、智慧工业、智慧金融、智慧城市、智慧生活、智慧交通”六大垂直领域，致力于构建智慧产业生态圈，赋能百行百业，共创智慧世界。
    </p>
    <h5>产品</h5>
    <p>5G超级SIM卡是由紫光国微推出的一款同时支持通信功能和大容量存储功能的新型SIM卡，可以全面兼容5G/4G/3G/2G网络，让大容量+大流量能够一卡兼得。同时，产品具备超大容量、安全存储、一键换机等强大功能，开创了私人数据中心，为用户定义了安心自由的数字化新生活。</p>
    <p>公司接触式CPU卡芯片采用增强8位CPU内核/32位CPU内核，具有从16KB EEPROM 到1MB以上大容量FLASH的数据存储空间。该芯片含DES、3DES算法，也可以支持国密安全算法，广泛用于移动通信SIM卡应用及社会保障卡应用。</p>
    <p>公司功率半导体器件产品主要包括500V~900V超结功率MOSFET、600V~700V Multi EPI超结功率MOSFET、20V~150V沟槽式功率MOSFET（N沟道和P沟道）、60V~100V双沟槽功率MOSFET、40V~1000V PLANAR VDMOS以及IGBT、IGTO、高压半桥Driver IC等。产品广泛应用于逆变器、交直流驱动、开关电源、充电器、LED照明、硬开关和高频电路等市场。</p>              
- name: 东方雨虹
  code: '2271'
  info: >
    <p>东方雨虹成立于1995年，二十余年来，为数以万计的重大基础设施建设、工业建筑和民用、商用建筑提供高品质的系统解决方案，已成为优质的建筑建材系统服务商。2008年公司上市，2020年营业收入突破217亿元，2008-2020年业绩增长30倍。公司陆续通过欧盟CE认证，德国EC1认证、美国FM认证、美国能源署（EPA）能源之星认证等多项国内国际认证，并获第十七届“全国质量奖”、2017年“全国质量标杆”“国家技术创新示范企业”等荣誉认定，上榜《财富》中国上市公司500强。</p>
- name: 宁德时代
  code: '300750'
  info: >
    <p>宁德时代新能源科技股份有限公司是全球领先的锂离子电池提供商，专注于新能源汽车动力电池系统、储能系统的研发、生产和销 售，致力于为全球新能源应用提供一流解决方案。公司在电池材料、电池系统、电池回收等产业链关键领 域拥有核心技术优势及可持续研发能力，形成了全面、完善的生产服务体系，并通过商业模式创新推动锂 离子电池作为优质能源储存载体的广泛应用。 </p>
    <h4>三大发展方向</h4>
    <p>三大发展方向:以可再生能源和储能为核心,实现固定式化石能源替代;以动力电池为核心
    实现移动式化石能源替代;以电动化+智能化为核心,实现市场应用的集成创新</p>
    <h4>主要产品及其用途 </h4>   
    <p>公司主要产品包括动力电池系统、储能系统和锂电池材料。
    动力电池系统 公司动力电池系统产品包括电芯、模组/电箱及电池包，应用领域涵盖新能源乘用车、新能源商用车以 及其他新能源出行工具及非道路移动机械等。公司动力电池系统能够满足启停、快充、长寿命、长续航里 程等多种功能需求，产品具有高能量密度、多循环次数、安全可靠等特点。公司根据应用领域及客户要求， 通过定制或联合研发等方式设计个性化产品方案，以满足客户对产品性能的不同需求。 在新能源乘用车领域，公司动力电池目前已广泛应用于纯电动乘用车、插电式混合动力乘用车、混合 动力乘用车及微混乘用车，形成包括高能量密度的三元高镍电池以及高性价比的磷酸铁锂电池等在内的完 整产品系列。 在新能源客车领域，公司动力电池目前已广泛应用于纯电动客车、插电式混合动力客车和混合动力客 车，如城市公交、商务旅游大巴、摆渡车等。在新能源卡车领域，公司产品可运用于电动重卡、轻型卡车 及物流车等商用车领域。在新能源二轮车领域，公司产品可应用于电动自行车、电动摩托车等领域，涵盖 共享、换电等商业模式。此外，公司还开发其他专用车市场并提供定制化解决方案，如环卫车、港口拖车 等。 公司动力电池产品还可广泛应用于电动船舶、叉车和工程机械等领域。 
    储能系统 公司储能系统产品包括电芯、模组/电箱和电池柜等，可用于发电、输配电和用电领域，涵盖太阳能或 风能发电储能配套、工业企业储能、商业楼宇及数据中心储能、储能充电站、通信基站后备电池、家用储 能等，可有效克服风能或太阳能发电输出不规则的特点、弥补线损功率补偿、跟踪计划削峰填谷，提高风 力及光伏发电系统能源利用率以及实现用电领域峰谷电之间的平衡。
    锂电池材料 公司可将废旧锂离子电池中的镍钴锰锂等有价金属通过加工、提纯、合成等工艺，生产三元前驱体等 锂离子电池材料，使镍钴锰锂等资源实现循环利用；公司也可通过外购材料进行锂离子电池材料的加工生 产。 
    </p>
    <h4>主要的业绩驱动因素</h4>
    <h6>1、汽车消费企稳回升</h6>
    <p> 
    国内方面，2020 年，国民经济克服了新冠肺炎疫情的严重冲击并稳步恢复。根据国家统计局，全年国 内生产总值同比增长 2.3%，分季度看，一季度同比下降 6.8%，二、三、四季度分别同比增长 3.2、4.9%、 6.5%。宏观经济稳步恢复有利于促进汽车消费，根据中国汽车工业协会数据，国内汽车市场从 4 月开始逐 步恢复，月度销量同比持续保持增长，2020 年我国新能源车销量达 136.7 万辆，同比增长 10.9%。 海外方面，受疫情影响，欧洲 30 国 2020 年实现乘用车注册量 1,187.8 万辆，同比下降 24.7%，但德国、 英国、法国等国为提振经济及减少碳排放，陆续出台鼓励政策，积极推动新能源车消费。根据欧洲汽车制造商协会数据，新能源乘用车全年注册量达 136.4 万辆，同比增长 143.8%。
    </p>  
    <h6>2、产业政策支持</h6> 
    <p> 
      (1）新能源车 国内市场，2020 年 4 月，国家财政部等部委发布新能源车免征购置税和补贴政策，免税和补贴政策延 续至 2022 年底，平缓补贴退坡力度和节奏。 海外市场，2019 年 4 月出台的欧洲碳排新政于 2020 年 1 月开始执行，各国加大对新能源车购车补贴 力度等政策扶持，单车补贴最高可达 9000 欧元，提振了新能源车消费。
      (2）储能 国内市场，2020 年 8 月，国家发改委、国家能源局联合发布《关于开展“风光水火储一体化”“源网荷 储一体化”的指导意见》，提出应在电源侧因地制宜采取风光水火多能互补，并适度增加一定比例储能，开 展区域（省）级、市（县）级、园区级源网荷储一体化，实现源网荷储深度协同。截至 2020 年底，10 余 个省份推出可再生能源配备储能政策，储能行业迎来发展契机。 海外市场，2020 年 9 月，欧盟委员会推出了《2030 年气候目标计划》，明确了将《巴黎协定》下的欧 盟国家自主贡献从先前的与 1990 年相比减排 40%的目标提高到至少减排 55%，并制定了各经济部门实现 目标的政策行动，其中到 2030 年计划可再生能源发电占比从目前的 32%提高至 65%以上，可再生能源装 机占比提升有望拉动储能需求增长。
    </p>
    <h6>3、新能源车消费需求增长</h6>
    <p>2020 年我国工信部公布的新能源车型有效目录共 6,800 余款车型，相较 2019 年多出 2200 余款车型， 可供消费者选择的车型增加。同时，新能源车主流车型续航里程提升，智能化属性增强，用户运营与服务 差异化为新能源车消费者带来良好体验。此外，充换电设施的进一步完善，改善新能源车使用条件。根据 中国电动车充电基础设施促进联盟数据，截至 2020 年底，全国公共类充电设施新增 46.2 万台，保有量达 80.7 万台。新能源车产品力提升和充换电基础设施的完善，推动消费者需求的快速增长。 
    2020年，公司克服了新冠病毒肺炎疫情带来的冲击，灵活应对市场及行业变化，持续加大研发力度， 优化产品结构和市场策略，稳步扩张产能以满足客户订单需求。同时，公司继续夯实业内最广泛的客户基 础，随着生产经营规模的持续扩大，公司在供应链管理、成本控制、市场开拓、技术迭代、客户服务等方 面的竞争优势逐渐凸显。 报告期内，公司实现营业总收入5,031,948.77万元，同比增长9.90%，归属于上市公司股东的净利润为 558,333.87万元，同比增长22.43%。报告期内，公司实现锂离子电池销量 46.84GWh，同比增长14.36%， 其中动力电池系统销量44.45GWh，同比增长10.43%。
    </p>  
- name: 五粮液
  code: '858'
  info: >
    <p>五粮液</p>
    <p>
    四川省宜宾五粮液集团有限公司（以下简称五粮液集团）是一家以酒业为主，多元化发展的大型国有企业集团。目前已形成“1+5”产业布局（酒业主业+大机械、大包装、大物流、大金融、大健康五大多元产业），拥有两家A股上市公司（000858五粮液和600793宜宾纸业），现有职工近5万人。
    五粮液集团拥有年产4万吨级的酿酒车间，拥有年产20万吨商品酒能力和60万吨原酒储存能力，是规模宏大的纯粮固态发酵白酒生产基地；拥有窖池3.2万余口，其中最古老的明初地穴式曲酒发酵窖池已持续使用650余年。五粮液产业园区规划面积18平方公里，是国家AAAA级旅游景区。2020年，五粮液集团公司实现销售收入1211亿元、利税433亿元；五粮液股份公司实现营业收入573.2亿元、增长14.4%，归属上市公司股东的净利润199.6亿元、增长14.7%。
    </p>
    <p>五粮液作为浓香型白酒典型代表和行业龙头企业，从盛唐时期的重碧酒，到宋代的姚子雪曲、明初的杂粮酒，再到1909年因“集五粮之精华而成玉液”正式得名，传承逾千载。五粮液集团前身是由长发升、利川永、全恒昌、天锡福、张万和、钟三和、听月楼、刘鼎兴等8家古传酿酒作坊联营组建而成；1959年更名为四川省地方国营宜宾五粮液酒厂；1998年，改制为宜宾五粮液集团有限公司, 宜宾五粮液股份有限公司在深交所挂牌上市（股票代码000858）。从1915年远赴巴拿马万国博览会扬名至今，五粮液已先后获得国家名酒、国家金质奖章、国家质量管理奖、中国最佳诚信企业、百年世博·百年金奖等上百项国内国际荣誉。2005年，五粮液明代地穴式曲酒发酵窖古窖泥被中国国家博物馆永久收藏。2008年，五粮液酒传统酿造技艺被列入国家级非物质文化遗产。五粮液老窖池是全国重点文物保护单位和国家工业遗产。2020年，五粮液品牌位居“全球品牌价值500强”第79位、“亚洲品牌500强”第37位、“中国品牌价值100强”第3位。</p> 
- name: 天赐材料
  code: '2709'
  info: >
    <p>广州天赐高新材料股份有限公司
    （以下简称“公司”）成立于2000年6月，并于2014年1月在深圳证券交易所中小板成功挂牌上市（证券简称：天赐材料，证券代码：002709）。自2000年成立以来，公司一直致力于精细化工新材料的研发、生产和销售，目前拥有锂离子电池材料、日化材料及特种化学品两大业务板块，拥有自主知识产权、核心技术和自主品牌，是国家高新技术企业、广东省创新型企业、广东优秀民营科技企业、广东省知识产权优势企业、广东省中小企业创新产业化示范基地、广东省战略性新兴产业培育企业、广东省自主创新100强企业。
    </p>
    <p>天赐材料始终重视自主研发和创新，拥有国家级企业技术中心、院士工作站、博士后科研工作站、广东省精细化工材料工程技术研发中心、广东省企业技术中心、江西省企业技术中心、广东省动力锂电池电解质材料工程实验室、电化学储能材料与技术教育部工程技术研发中心，已经形成了具有国际竞争力的精细化学品研发、生产和销售的总体能力，依靠在精细化工领域多年的经验及技术的积累，建立了以研发引导技术、以技术推动产品的发展模式。基于柔性中试体系及行业领先的化工工程能力，天赐材料发展出锂离子电池材料、日化材料及特种化学品两大业务板块。
    </p>
    <p>天赐材料是国内主要的锂离子电池材料、个人护理品功能材料生产商之一，拥有同行业中规模较大的研发中心，形成了研究-技术-应用的产品一体化评价体系，在国内外享有重要的行业地位、技术水平处于国内领先，并具有较大的影响力及行业带头示范作用。
    天赐材料以创造完美品质为使命，通过不断地研发安全、环保、性能优良、具备国际品质的精细化工原料，为顾客生产和制造稳定、均一、可靠的产品，使顾客获取更优的价值。公司愿景是成为精细化工行业的国际化一流企业，致力于建立精细化工行业的高档品牌形象，产品力求达到国际水准，业务上成为国际知名企业。
    </p> 
- name: 长春高新
  code: '661'
  info: >
    <p>
    1993年6月，长春高新技术产业（集团）股份有限公司由长春高新技术产业发展总公司独家发起设立，总股本13750万股。
    1996年12月18日，公司股票在深圳证券交易所挂牌上市，是东北地区最早的一批上市公司之一。
    上市20余年来，长春高新从公司成立之初的以高新区基础设施建设为主成功转型，成为一家专注于医药科技创新领域，实施产业投资的企业集团。公司始终秉承“创新、专注、包容、共享、发展”的企业文化，践行为客户创造价值、为员工创造机会、为股东创造效益、为社会承担责任的核心价值观，明确以生物制药为主、房地产为辅的产业定位，形成了基因工程药、生物疫苗、现代中药三大产业发展平台，实现了金赛药业、百克生物、华康药业、高新地产“四驾马车”鼎力发展格局，开创了共享发展、合作共赢的良好局面。
    公司经营业绩持续增长，2017、2018年在全国医药工业百强排名分别为73、56名。
    </p>
    <h5>打造医药产业为主、房地产业为辅的产业格局</h5>
    <p>
    长春高新作为国内基因工程生物制药具有一定影响力的企业，在产品研发、生产保障、营销管理等核心问题上孜孜以求，不断挖掘并提升企业价值和内涵。
    经过多年的蓄势和积淀，目前公司在生物制药、新产品研发、特色地产、产业投资等方面愈发完善，核心竞争力不断强化。坚持投资控股、战略管控管理模式，贯彻医药产业为主、房地产业为辅的产业战略，在追求整体协同和收益最大化的同时鼓励企业个性化发展。
    医药产品覆盖了创新基因工程制药、生物疫苗、现代中药等多个医药细分领域，塑造了良好的品牌形象并逐步赢得市场认可。医药产业布局方面，坚持以市场为导向，一方面在现有产品工艺设施的基础上，利用自身的技术和研发优势，产品创新能力不断加强；另一方面通过创新项目的成功孵化和产业化培育，打造并形成目前在国内基因工程制药、生物疫苗、现代中药领域具有一定的技术优势和市场优势的产品结构。
    </p>
- name: 兆易创新
  code: '603986'
  info: >
    兆易创新成立于2005，是一家领先的无晶圆厂半导体公司，致力于开发先进的存储器技术和IC解决方案。2016年8月，公司在上海证券交易所成功上市。公司在中国北京、上海、深圳、合肥、西安、成都、苏州、香港和台湾，美国、韩国、日本、英国、新加坡等多个国家和地区均设有分支机构和办事处，营销网络遍布全球，为客户提供优质便捷的本地化支持服务。
    公司核心管理团队由来自世界各地的高级管理人员组成，具有丰富的研发及管理经验，技术研发核心成员来自清华、北大、复旦、中科院等国内微电子领域顶尖院所，硕士及以上学历占比超过60%。同时，我们也积极引进具有国际视野的专业人才，跟踪最新技术发展方向，提升公司技术产品的领先性。                    
    公司的核心产品线为FLASH、32位通用型 MCU及智能人机交互传感器芯片及整体解决方案，公司产品以“高性能、低功耗”著称，为工业、汽车、计算、消费类电子、物联网、移动应用以及网络和电信行业的客户提供全方位服务。在中国市场，我们的SPI NOR FLASH®市场占有率为第一，同时也是全球排名前三的供应商之一，累计出货量超130亿颗，年出货量超28亿颗；我们的MCU作为中国32位通用MCU领域的主流产品，以24个系列350余款产品选择，覆盖率稳居市场前列，并且累计出货量已超过4亿颗。我们的触控和指纹识别芯片广泛应用在国内外知名移动终端厂商，是国内仅有的两家的可量产供货的光学指纹芯片供应商。
    公司在质量管理方面有严格的标准与要求，已获得ISO 9001、ISO 14001等国际质量体系认证，同时积极推进产业整合，拓展战略布局，在已有的微控制器、存储器基础上，布局物联网领域人机交互技术，并与全球多家领先晶圆厂、封装测试厂达成战略合作伙伴关系，通过加强产业上下游合作、优化供应链管理，共同推进半导体领域的技术创新。
- name: 玉马遮阳
  code: '300993'
  info: >
    我也不知道他是干嘛的
  
  name: 神奇B股
  code: '900904'
  info: >
    神奇吧！太神奇了。