name: Quarterly update on earning reports

on:
  schedule:
    - cron: '0 6 1 * *'  # 6:00 first day of each month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update earnings reports
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm ci & npm run updatedb all && npm run build

      - name: publish to netlify site
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: 7591e6db-1195-474a-a41b-e6edfac69f2a
          NETLIFY_AUTH_TOKEN: x2q6en5jXIvrQpvyNgBNr_XWPvZYdm7Yls6GNQvRVSo

