name: Scheduled update

on:
  schedule:
    - cron: '0 23,6 * * *'  # 6 am every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update stock data
        uses: nick-invision/retry@v2.4.0
        with:
          # build can be slow due to the request for live stock price
          timeout_seconds: 120
          max_attempts: 3
          retry_on: timeout
          command: npm ci && npm run build
      - name: publish to netlify site
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: 7591e6db-1195-474a-a41b-e6edfac69f2a
          NETLIFY_AUTH_TOKEN: x2q6en5jXIvrQpvyNgBNr_XWPvZYdm7Yls6GNQvRVSo
